from src.datamodules.inaturalist2017 import INaturalist2017DataModule
from src.datamodules.inaturalist_emb_contexts import INaturalistEmbContextsDataModule
from src.datamodules.waterbirds import WaterbirdsDataModule
from src.datamodules.waterbirds_emb_contexts import WaterbirdsEmbContextsDataModule
from src.datamodules.cub import CUBDataModule
from src.datamodules.cub_emb_contexts import CUBEmbContextsDataModule
from src.datamodules.imagenet import ImagenetDataModule
from src.datamodules.imagenet_emb_contexts import ImagenetEmbContextsDataModule
