from src.datamodules.inaturalist2017 import INaturalist2017DataModule
from src.datamodules.inaturalist_emb_contexts import INaturalistEmbContextsDataModule
from src.datamodules.waterbirds import WaterbirdsDataModule
