from src.datamodules.waterbirds import WaterbirdsDataModule
from src.datamodules.waterbirds_emb_contexts_v2 import WaterbirdsEmbContextsDataModuleV2
from src.datamodules.multinli import MultiNLIDataModule
from src.datamodules.multinli_emb_contexts_v2 import MultiNLIEmbContextsDataModuleV2
