name: train
seed: 0
print_config: True
ignore_warnings: False

checkpoint_path: null

defaults:
  - datamodule: waterbirds_emb_contexts  # Options: inaturalist_emb_contexts, waterbirds_emb_contexts, celeba_emb_contexts
  - encoding_extractor: dinov2_vitb14 # Options: dinov2_vitb14, resnet50, resnet18
  - model: incontext_learner_gptj_80m
  - optimizer: adam
  - scheduler: warmup_cosine_annealing
  - trainer: default
  - loggers: [aim]
  - callbacks: [lr_monitor, model_checkpoint]
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/runs/${name}/${now:%Y-%m-%d_%H-%M-%S} # IMPORTANT: Directory name AUTO-UPDATED with 'aim' logger's HASH when 'aim' is ENABLED
  job:
    chdir: True
