_target_: src.datamodules.MultiNLIEmbContextsDataModuleV2
name: multinli_emb_contexts

context_class_size: 64

context_group_proportions: [0.45, 0.05, 0.05, 0.45]
train_query_group_proportions: [0.25, 0.25, 0.25, 0.25]
eval_query_group_proportions: [0.25, 0.25, 0.25, 0.25]

root_dir: ${oc.env:DATA_ROOT_DIR}
encoding_extractor: ${encoding_extractor.name}

train_len: 2000000
eval_len: 1024 # 2^n, because CombinedDataloader removes the last non-full batch

batch_size: 32
num_workers: 4

reverse_task: False

rotate_encodings: False
n_rotation_matrices: 10000  # produces roughly 40m different examples
allow_rotated_eval: False

permute_input_dim: False

val_sets: [train, train_val, train_test, test]  # the order here should match the order in the combined loader
